import type { RFPSubmission } from './types'

export const mockRFPData: RFPSubmission[] = [
  {
    id: '1',
    clientName: 'Acme Insurance Corp',
    poCs: [
      { name: 'Sarah Johnson', email: 'sarah.johnson@acme.com' },
      { name: 'Mike Davis', email: 'mike.davis@acme.com' },
    ],
    geo: 'US/CA',
    submissionDate: '2025-09-24',
    guidewireProducts: ['Policy Center', 'Billing Center', 'Claim Center'],
    insuranceProducts: ['Auto', 'Excess Casualty', 'WC', 'CL'],
    commercial: true,
    personal: true,
    specialty: false,
    implementation: true,
    productStrategy: true,
    programTesting: false,
    pmo: true,
    amsOperate: false,
    cloudSelfManaged: 'Cloud',
    cloudPlatform: 'AWS',
    newMigrationUpgrade: 'Migration',
    liveInFlightRfp: ['Live', 'In-Flight'],
    outcome: 'Won',
    totalImplementations: 3,
    valueBreakdown: [
      { category: 'Implementation Lite + Full', value: 10400000 },
      { category: 'Full', value: 10000000 },
      { category: 'L2-L4 Support', value: 5800000 },
    ],
    numberOfHours: 123570,
    duration: { value: 36, unit: 'months' },
    deltaVariance: 0.1,
    numberOfIntegrations: 28,
    artifactPresent: 'Yes',
    projectData: {
      name: 'Acme Migration Project Docs',
      link: 'https://sharepoint.company.com/sites/acme-migration',
    },
    comments: 'High priority client with phased rollout approach. Estimated completion Q3 2026.',
    documentsAvailable: ['RFP_Acme_2025.pdf', 'Technical_Requirements.docx', 'Implementation_Plan.xlsx'],
  },
  {
    id: '2',
    clientName: 'Global Risk Solutions',
    poCs: [
      { name: 'Mike Chen', email: 'mike.chen@globalrisk.com' },
    ],
    geo: 'AUS',
    submissionDate: '2025-08-15',
    guidewireProducts: ['Claim Center'],
    insuranceProducts: ['Auto', 'CL'],
    commercial: true,
    personal: false,
    specialty: true,
    implementation: true,
    productStrategy: true,
    programTesting: true,
    pmo: true,
    amsOperate: true,
    cloudSelfManaged: 'Cloud',
    cloudPlatform: 'GCP',
    newMigrationUpgrade: 'New',
    liveInFlightRfp: ['Live'],
    outcome: 'Pending',
    totalImplementations: 2,
    valueBreakdown: [
      { category: 'Implementation', value: 4500000 },
      { category: 'Support', value: 1200000 },
    ],
    numberOfHours: 98740,
    duration: { value: 28, unit: 'weeks' },
    deltaVariance: null,
    numberOfIntegrations: 15,
    artifactPresent: 'Yes',
    projectData: {
      name: 'Global Risk Implementation',
      link: 'https://sharepoint.company.com/sites/global-risk',
    },
    comments: 'Awaiting client final budget approval. Expected decision by end of Q4 2025.',
    documentsAvailable: ['Requirements_Global.pdf', 'Budget_Proposal.xlsx'],
  },
  {
    id: '3',
    clientName: 'European Insurance Group',
    poCs: [
      { name: 'Anna Mueller', email: 'anna.mueller@euroinsurance.eu' },
      { name: 'Klaus Schmidt', email: 'klaus.schmidt@euroinsurance.eu' },
      { name: 'Sophie Laurent', email: 'sophie.laurent@euroinsurance.eu' },
    ],
    geo: 'US',
    submissionDate: '2025-07-10',
    guidewireProducts: ['Policy Center', 'Billing Center'],
    insuranceProducts: ['Personal', 'Excess Casualty'],
    commercial: false,
    personal: true,
    specialty: true,
    implementation: true,
    productStrategy: false,
    programTesting: true,
    pmo: true,
    amsOperate: false,
    cloudSelfManaged: 'Self-Managed',
    newMigrationUpgrade: 'Upgrade',
    liveInFlightRfp: ['In-Flight', 'RFP'],
    outcome: 'Lost',
    totalImplementations: 5,
    valueBreakdown: [
      { category: 'Upgrade Base', value: 8200000 },
      { category: 'Enhancement Modules', value: 2100000 },
      { category: 'Training & Support', value: 1500000 },
    ],
    numberOfHours: 145600,
    duration: { value: 48, unit: 'months' },
    deltaVariance: -2.5,
    numberOfIntegrations: 18,
    artifactPresent: 'No',
    projectData: {
      name: 'European Upgrade Project',
      link: 'https://sharepoint.company.com/sites/europe-upgrade',
    },
    comments: 'Competitor won with lower pricing. Internal analysis shows 15% cost difference.',
    documentsAvailable: ['Competitor_Analysis.pdf'],
  },
  {
    id: '4',
    clientName: 'Latin America Insurers Ltd',
    poCs: [
      { name: 'Carlos Rodriguez', email: 'carlos.rodriguez@lataminsurance.com' },
      { name: 'Isabella Santos', email: 'isabella.santos@lataminsurance.com' },
    ],
    geo: 'AUS',
    submissionDate: '2025-06-20',
    guidewireProducts: ['Policy Center'],
    insuranceProducts: ['WC', 'CL'],
    commercial: true,
    personal: false,
    specialty: false,
    implementation: true,
    productStrategy: true,
    programTesting: false,
    pmo: false,
    amsOperate: true,
    cloudSelfManaged: 'Cloud',
    cloudPlatform: 'Azure',
    newMigrationUpgrade: 'New',
    liveInFlightRfp: ['Live'],
    outcome: 'Won',
    totalImplementations: 1,
    valueBreakdown: [
      { category: 'Base Implementation', value: 3200000 },
      { category: 'Year 1 Support', value: 800000 },
    ],
    numberOfHours: 52300,
    duration: { value: 20, unit: 'weeks' },
    deltaVariance: 1.8,
    numberOfIntegrations: 8,
    artifactPresent: 'Yes',
    projectData: {
      name: 'LATAM New Implementation',
      link: 'https://sharepoint.company.com/sites/latam-new',
    },
    comments: 'Fast-track implementation for Q2 2026 launch. Client committed to aggressive timeline.',
    documentsAvailable: ['LATAM_SOW.pdf', 'Timeline_Approved.docx', 'Budget_Signed.pdf'],
  },
  {
    id: '5',
    clientName: 'Middle East Insurance Syndicate',
    poCs: [
      { name: 'Fatima Al-Mansouri', email: 'fatima.almansouri@meinsurance.ae' },
      { name: 'Ahmed Hassan', email: 'ahmed.hassan@meinsurance.ae' },
    ],
    geo: 'US/CA',
    submissionDate: '2025-05-08',
    guidewireProducts: ['Billing Center', 'Claim Center'],
    insuranceProducts: ['Auto', 'WC'],
    commercial: true,
    personal: true,
    specialty: false,
    implementation: false,
    productStrategy: true,
    programTesting: true,
    pmo: true,
    amsOperate: true,
    cloudSelfManaged: 'Cloud',
    cloudPlatform: 'AWS',
    newMigrationUpgrade: 'Migration',
    liveInFlightRfp: ['In-Flight'],
    outcome: 'Pending',
    totalImplementations: 4,
    valueBreakdown: [
      { category: 'Migration Services', value: 6500000 },
      { category: 'System Integration', value: 3200000 },
      { category: 'Support & Maintenance', value: 2100000 },
    ],
    numberOfHours: 187450,
    duration: { value: 72, unit: 'weeks' },
    deltaVariance: 4.3,
    numberOfIntegrations: 22,
    artifactPresent: 'Yes',
    projectData: {
      name: 'Middle East Migration',
      link: 'https://sharepoint.company.com/sites/middle-east-migration',
    },
    comments: 'Regulatory compliance requirements being finalized. Awaiting government approvals.',
    documentsAvailable: ['Regulatory_Framework.pdf', 'Compliance_Checklist.xlsx'],
  },
  {
    id: '6',
    clientName: 'Pacific Regional Insurance',
    poCs: [
      { name: 'James Thompson', email: 'james.thompson@pacificregional.com' },
    ],
    geo: 'US',
    submissionDate: '2025-04-12',
    guidewireProducts: ['Policy Center', 'Billing Center'],
    insuranceProducts: ['Personal', 'Excess Casualty', 'WC'],
    commercial: false,
    personal: true,
    specialty: true,
    implementation: true,
    productStrategy: true,
    programTesting: true,
    pmo: true,
    amsOperate: false,
    cloudSelfManaged: 'Self-Managed',
    newMigrationUpgrade: 'Upgrade',
    liveInFlightRfp: ['Live', 'RFP'],
    outcome: 'Won',
    totalImplementations: 2,
    valueBreakdown: [
      { category: 'Upgrade Platform', value: 7800000 },
      { category: 'Advanced Features', value: 2400000 },
      { category: 'Training Programs', value: 900000 },
    ],
    numberOfHours: 105200,
    duration: { value: 32, unit: 'months' },
    deltaVariance: 2.1,
    numberOfIntegrations: 11,
    artifactPresent: 'Yes',
    projectData: {
      name: 'Pacific Upgrade Program',
      link: 'https://sharepoint.company.com/sites/pacific-upgrade',
    },
    comments: 'Successful upgrade with improved system performance. Client very satisfied with outcomes.',
    documentsAvailable: ['Final_Report.pdf', 'Performance_Metrics.xlsx', 'Handover_Documentation.docx', 'Training_Materials.zip'],
  },
]
